const data = [
  {
    saveMoney: {
      EconomicProducts: [
        {
          name: "Սպիտակեցնող նյութ «Deschlor» 1.1կգ",
          id: "otbelivatel-deschlor-belizna-1-1kg-pl-butylka-_89619/",
          image:
            "https://supermarket.am/images/cache/b67/ec4/trim_835510a2131e30e2cca82abe9a5efd8d.JPG",
          price: 390,
          count: 1,
          class: "Տնտեսական ապրանքներ",
          description: "Մաքրող հեղուկ",
          madeIn: "Հայաստան",
          brand: "Deschlor",
          productCode: 989817,
          productID: 89619,
          category: "topsale",
          storageMethod: "Պահել մութ և չոր տեղում: 5-20 °C պայմաններում:",
        },
        {
          name: "Ժավել-գել 1լ",
          id: "zhavel-gel-1l_278995/",
          image:
            "https://supermarket.am/images/cache/03e/ec2/trim_2a9aa2de41f1c940d1582c04251efeac.JPG",
          price: 720,
          count: 1,
          class: "Տնտեսական ապրանքներ",
          description: "Ժավել-գել",
          madeIn: "Հայաստան",
          brand: "Deschlor",
          productCode: 167170,
          productID: 278995,
          category: "topsale",
          storageMethod: "Պահել մութ և չոր տեղում: 5-20 °C պայմաններում:",
        },
      ],
      Սննդամթերք: [
        {
          name: "Ըմպելիք էներգետիկ «Red Bull» 0.25լ",
          id: "napitok-energeticheskiy-red-bull-0-25l-zh-b_22317/",
          image:
            "https://supermarket.am/images/cache/80a/ed9/trim_0bf2afb31837ec601713bde78fef68a7.jpg",
          price: 390,
          count: 1,
          class: "Հյութեր և ըմպելիքներ",
          description:
            "Էներգետիկ ըմպելիք` տաուրինով: Առույգացնում է մարմինն ու միտքը:",
          madeIn: "Հայաստան",
          brand: "Red Bull",
          productCode: 11483,
          productID: 22317,
          category: "topsale",
          storageMethod: "Պահել մութ և չոր տեղում: 5-20 °C պայմաններում:",
        },
        {
          name: "Ձիթապտուղ սև՝ առանց կորիզ «Coopoliva» 385գ",
          id: "olivki-coopoliva-bez-kostochki-chernye-385g-zh-b-ispaniya_22731/",
          image:
            "https://supermarket.am/images/cache/80a/ed9/trim_0bf2afb31837ec601713bde78fef68a7.jpg",
          price: 740,
          count: 1,
          class: "Հյութեր և ըմպելիքներ",
          description:
            "Սև ձիթապտուղ` առանց կորիզի: Սև ձիթապտուղները սովորաբար մատուցվում են մսի, թռչնամսի հետ, ինչպես նաև օգտագործվում են զանազան սոուսներ և բանջարեղենի մածուկներ պատրաստելիս:",
          madeIn: "Իսպանիա",
          brand: "Coopoliva",
          productCode: 102043,
          productID: 22731,
          category: "topsale",
          storageMethod: "Պահել մութ և չոր տեղում: 5-20 °C պայմաններում:",
        },
      ],
    },
    electronics: {
      "TV.monitor": [
        {
          name: "Հեռուստացույց LED «SAMSUNG QE55Q70AAUXRU»",
          id: "_1298798/",
          image:
            "https://supermarket.am/images/cache/cce/d4a/trim_9af5dd39563b11cb1fe427d6001f3690.png",
          price: 729900,
          count: 1,
          class: "Էլեկտրոնիկա",
          description: "",
          madeIn: "Ռուսաստան",
          brand: "SAMSUNG",
          productCode: 298161,
          productID: 1298798,
          category: "save",
          storageMethod: "Պահել մութ և չոր տեղում: 5-20 °C պայմաններում:",
        },
        {
          name: "Հեռուստացույց LED «SONY KD50X81JR»",
          id: "_1298858/",
          image:
            "https://supermarket.am/images/cache/12f/f1a/trim_1b5a74ee51e51491f12914aabc0b42b6.png",
          price: 713000,
          count: 1,
          class: "Էլեկտրոնիկա",
          description: "",
          madeIn: "Մալազիա",
          brand: "SONY",
          productCode: 298213,
          productID: 1298858,
          category: "save",
          storageMethod: "Պահել մութ և չոր տեղում: 5-20 °C պայմաններում:",
        },
      ],
      careItems: [
        {
          name: "Մազերի էլեկտրական սանր «Philips PH HP8661/00»",
          id: "_1311947/",
          image:
            "https://supermarket.am/images/cache/f84/8f2/trim_4958fa35ed8c73fa2c1f305c931ff3b7.png",
          price: 19900,
          count: 1,
          class: "Էլեկտրոնիկա",
          description: "",
          madeIn: "Չինաստան",
          brand: "Philips",
          productCode: 298936,
          productID: 1311947,
          category: "save",
          storageMethod: "Պահել մութ և չոր տեղում: 5-20 °C պայմաններում:",
        },
        {
          name: "Մազերի էլեկտրական սանր «Philips PH HP8661/00»",
          id: "_1311948/",
          image:
            "https://supermarket.am/images/cache/f84/8f2/trim_4958fa35ed8c73fa2c1f305c931ff3b7.png",
          price: 19900,
          count: 1,
          class: "Էլեկտրոնիկա",
          description: "",
          madeIn: "Չինաստան",
          brand: "Philips",
          productCode: 298936,
          productID: 1311947,
          category: "novelty",
          storageMethod: "Պահել մութ և չոր տեղում: 5-20 °C պայմաններում:",
        },
      ],
    },
  },
];
